version: '3.8'

services:
  recipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-app
    ports:
      - "3000:3000" # Map port 3000 on host to 3000 in the container
    environment:
      DB_USER: postgres
      DB_HOST: recipe-db
      DB_NAME: recipe_db
      DB_PORT: 5432
      DB_PASSWORD_FILE: /run/secrets/postgres_password # Secure password via Docker secret
      PORT: 3000
    depends_on:
      - recipe-db
    secrets:
      - postgres_password

  recipe-db:
    image: postgres:13
    container_name: recipe-db
    ports:
      - "5432:5432" # Map port 5432 on host to 5432 in the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recipe_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password # Secure password via Docker secret
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./secrets/postgres_password # Path to your secret file

volumes:
  postgres-data:
